#Display all orders with customer names.
select order_id, customer_name
from orders o
join customers c on o.customer_id = c.customer_id;

#Show product names and quantities for each order.
select o.order_id, p.product_name, o.quantity
from orderdetails o
join products p on o.product_id = p.product_id;

#Display employee name who handled each order.
select o.order_id, e.employee_name
from orders o
join employees e on o.employee_id = e.employee_id;

#Show all customers and their orders (including customers without orders).
select customer_name,order_id from customers c
left join orders o on c.customer_id = o.customer_id;

#Display total number of orders handled by each employee.
select employee_name,count(order_id) as total_orders_handled 
from orders o
join employees e on o.employee_id =e.employee_id
group by employee_name;


#Find customers who placed more than 1 order.
select customer_name
from customers c
where customer_id in (select customer_id from orders group by customer_id having count(order_id)>1);

#Display products with price higher than the average product price.
select product_name,price from products p
where price>(select avg(price) from products);

#Find the customer who placed the highest number of orders.
select c.customer_name
from customers c
where c.customer_id = (select customer_id from orders
group by customer_id
order by COUNT(order_id) desc
limit 1);

#Show orders where total quantity is greater than the average quantity.
select order_id from orderdetails
group by order_id
having SUM(quantity) > (select avg(quantity) from orderdetails);

#Find employees who handled more orders than the average employee
select employee_id 
from orders 
group by employee_id 
having COUNT(order_id) > (select avg(order_count) 
from (select COUNT(*) as order_count
from orders group by employee_id) as o);


#Using CTE, calculate total sales amount for each order.
with sales_cte as(select od.order_id,sum(od.quantity * p.price) as total_sales
from orderdetails od 
join products p on od.product_id = p.product_id
group by order_id)
select * from sales_cte order by total_sales desc;

#Using CTE, find customers whose total purchase amount is greater than 20,000.
with purchase_cte as
(select customer_name,sum(quantity*price) as total_purchase
from orderdetails od 
join products p on od.product_id = p.product_id
join orders o on od.order_id = o.order_id
join customers c on o.customer_id = c.customer_id
group by customer_name)
select * from purchase_cte where total_purchase >20000;

#Using CTE, display the total revenue generated by each product category.
with category_cte as(
select p.category,sum(od.quantity * p.price) as total_revenue
from products p
join orderdetails od on p.product_id = od.product_id
group by p.category)
select * from category_cte;

#Using CTE, find the top 3 customers based on total spending.
with spend_cte as
(select customer_name,sum(quantity*price) as total_spend
from orderdetails od 
join products p on od.product_id = p.product_id
join orders o on od.order_id = o.order_id
join customers c on o.customer_id = c.customer_id
group by customer_name)
select * from spend_cte 
order by total_spend desc
limit 3;

#Assign rank to customers based on total purchase amount.
with rank_cte as(select customer_name,sum(quantity*price) as total_purchase
from orderdetails od 
join products p on od.product_id = p.product_id
join orders o on od.order_id = o.order_id
join customers c on o.customer_id = c.customer_id
group by customer_name)
select *,rank() over(order by total_purchase desc) as row_rank from rank_cte;

#Display cumulative sales amount by order date.
with cumulative_cte as
(select o.order_date,
sum(od.quantity * p.price) as sales
from orders o
join orderdetails od on o.order_id = od.order_id
join Products p on od.product_id = p.product_id
group by o.order_date)
select *,sum(sales) over (order by order_date) as cumulative_sales from cumulative_cte;

#Display running total of sales for each employee.
select e.employee_id,e.employee_name,
SUM(od.quantity * p.price) as sales,
sum(SUM(od.quantity * p.price)) over (partition by o.employee_id order by o.order_date) as running_total
FROM employees e
join orders o on e.employee_id= o.employee_id
join orderdetails od on o.order_id = od.order_id
join Products p on od.product_id = p.product_id
GROUP BY e.employee_id,e.employee_name,o.order_date;

#Find the highest priced product in each category.
with high_cte as(select product_name,category,price,
row_number() over(partition by category order by price desc) as row_num
from products)
select * from high_cte where row_num = 1;

#Find customers who never placed an order.
select customer_id,customer_name from customers 
where customer_id not in(select customer_id from orders);

#Find the second highest selling product.
select p.product_name,sum(od.quantity) as total_sold
from products p
join orderdetails od on p.product_id = od.product_id
group by product_name
order by total_sold desc
limit 1 offset 1;

#Identify duplicate orders placed on the same day.
select order_date,count(*)
from orders
group by order_date
having count(*) >1;

#Total Revenue
select sum(od.quantity * p.price) as total_revenue
from orderdetails od
join products p on od.product_id = p.product_id;

#Monthly Sales Trend
select date_format(o.order_date, '%Y-%m') as month,
sum(od.quantity * p.price) as revenue
from orders o
join orderdetails od on o.order_id = od.order_id
join products p on od.product_id = p.product_id
group by month
order by month;

#Top 5 products
select p.product_name,
sum(od.quantity) as total_sold
from products p
join orderdetails od on p.product_id = od.product_id
group by p.product_name
order by total_sold desc
limit 5;
